Added wait for scale of deployment
jcechace/RbShift pull request #41
Opened 2018-06-05 13:05 UTC by jsmadis

2018-06-05 13:07 UTC, pestanko approved these changes

2018-06-06 11:11 UTC, mijaros requested changes
Please move the scale logic to the ReplicationController.

2018-07-11 11:53 UTC, mijaros approved these changes

2018-07-29 21:28 UTC, jcechace approved these changes

2018-07-29 21:28 UTC, merged